import type { Metadata } from "next";
import PublicBusinessShell, { LegalDocument } from "@/components/public/PublicBusinessShell";
import styles from "@/components/public/PublicBusiness.module.css";
import { BUSINESS } from "@/lib/public-business";

export const metadata: Metadata = { title: "Política de privacidad | Tarot Celestial", description: "Información sobre el tratamiento de datos personales en Tarot Celestial.", alternates: { canonical: `${BUSINESS.website}/privacidad` } };

export default function PrivacyPage() {
  return <PublicBusinessShell activePath="/privacidad"><LegalDocument eyebrow="Protección de datos" title="Política de privacidad" intro="Información transparente sobre cómo tratamos los datos personales necesarios para prestar el servicio.">
    <section><h2>1. Responsable del tratamiento</h2><dl className={styles.dataList}><div><dt>Responsable</dt><dd>{BUSINESS.legalName}</dd></div><div><dt>Nombre comercial</dt><dd>{BUSINESS.commercialName}</dd></div><div><dt>NIF/NIE</dt><dd>{BUSINESS.taxId}</dd></div><div><dt>Dirección</dt><dd>{BUSINESS.addressLines.join(", ")}</dd></div><div><dt>Contacto</dt><dd><a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a></dd></div></dl></section>
    <section><h2>2. Datos tratados</h2><p>Podemos tratar datos identificativos y de contacto, información necesaria para gestionar la cuenta y la consulta, datos de contratación y facturación, comunicaciones con atención al cliente y datos técnicos básicos de seguridad. Los datos completos de tarjeta son tratados por el proveedor de pagos y no deben enviarse por correo electrónico.</p></section>
    <section><h2>3. Finalidades y bases jurídicas</h2><ul><li><strong>Gestionar la cuenta, compra y prestación del servicio:</strong> ejecución del contrato y medidas precontractuales.</li><li><strong>Facturación y obligaciones fiscales:</strong> cumplimiento de obligaciones legales.</li><li><strong>Atención de solicitudes e incidencias:</strong> ejecución del contrato e interés legítimo en atender y proteger el servicio.</li><li><strong>Seguridad y prevención del fraude:</strong> interés legítimo y, cuando corresponda, cumplimiento legal.</li><li><strong>Comunicaciones comerciales:</strong> únicamente cuando exista consentimiento u otra base legítima aplicable; el usuario puede oponerse o retirar el consentimiento.</li></ul></section>
    <section><h2>4. Conservación</h2><p>Los datos se conservarán mientras exista una relación contractual o una cuenta activa. Después se mantendrán bloqueados durante los plazos necesarios para atender obligaciones fiscales, contables, de consumo, prevención del fraude y posibles responsabilidades. Los datos tratados únicamente mediante consentimiento se conservarán hasta su retirada, salvo que proceda otro plazo legal.</p></section>
    <section><h2>5. Destinatarios y proveedores</h2><p>Los datos podrán ser tratados por proveedores necesarios para alojamiento web, comunicaciones, telefonía, soporte, almacenamiento y procesamiento de pagos, bajo las garantías contractuales aplicables. También podrán comunicarse a administraciones, autoridades o entidades financieras cuando exista una obligación legal o sea necesario para gestionar una operación solicitada.</p><p>Si un proveedor trata datos fuera del Espacio Económico Europeo, se aplicarán los mecanismos y garantías exigidos por la normativa de protección de datos.</p></section>
    <section><h2>6. Derechos</h2><p>Puedes solicitar el acceso, rectificación, supresión, oposición, limitación y portabilidad de tus datos, así como retirar un consentimiento, escribiendo a <a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a> e indicando el derecho que deseas ejercer. Podremos pedir información razonable para verificar tu identidad.</p><p>Si consideras que el tratamiento no es adecuado, puedes reclamar ante la <a href="https://www.aepd.es" rel="noreferrer">Agencia Española de Protección de Datos</a>.</p></section>
    <section><h2>7. Seguridad y decisiones automatizadas</h2><p>Se aplican medidas técnicas y organizativas orientadas a proteger los datos frente a pérdida, alteración o acceso no autorizado. No se adoptan decisiones con efectos jurídicos para el usuario basadas únicamente en tratamientos automatizados de sus datos.</p></section>
    <section><h2>8. Actualizaciones</h2><p>Esta política puede actualizarse para reflejar cambios legales o del servicio. La versión aplicable estará siempre disponible en esta dirección pública.</p></section>
  </LegalDocument></PublicBusinessShell>;
}
