"use client";
import { useCallback,useEffect,useState } from "react";
import { Gem,LockKeyhole,Shield,Sparkles,Sprout,Heart,Orbit } from "lucide-react";
import ClienteLayout from "@/components/cliente/ClienteLayout";
import { supabaseClienteBrowser } from "@/lib/supabase-browser";
import styles from "./Ritual.module.css";
const sb=supabaseClienteBrowser();
function Visual({slug,progress,asset}:{slug:string,progress:number,asset?:string|null}){if(asset)return <video className={styles.video} src={asset} autoPlay muted loop playsInline/>;const Icon=slug==="proteccion"?Shield:slug==="sanacion"?Heart:slug==="armonizacion"?Orbit:slug==="limpieza"?Gem:Sprout;return <div className={styles.visual} data-theme={slug} style={{"--progress":`${progress}%`} as any}><span className={styles.aura}/><span className={styles.orbit}/><Icon size={104}/><span className={styles.spark}>✦</span></div>}
export default function RitualPage(){const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true);const load=useCallback(async()=>{const token=(await sb.auth.getSession()).data.session?.access_token;if(!token)return;const r=await fetch("/api/cliente/ritual",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const j=await r.json();setData(j);setLoading(false)},[]);useEffect(()=>{void load()},[load]);useEffect(()=>{if(!data?.ritual?.id)return;const ch=sb.channel(`ritual-${data.ritual.id}`).on("postgres_changes",{event:"*",schema:"public",table:"client_rituals",filter:`id=eq.${data.ritual.id}`},()=>void load()).subscribe();const timer=setInterval(()=>void load(),60000);return()=>{clearInterval(timer);void sb.removeChannel(ch)}},[data?.ritual?.id,load]);return <ClienteLayout title="Mi Ritual" subtitle="Tu espacio privado para seguir cada etapa de tu experiencia." eyebrow="Tarot Celestial · Experiencia privada">{loading?<section className={styles.state}>Preparando tu espacio ritual…</section>:!data?.diamond?<Locked rank={data?.rank}/>:!data?.ritual?<Empty/>:<Active ritual={data.ritual} history={data.history||[]}/>}</ClienteLayout>}
function Locked({rank}:{rank?:string}){return <section className={styles.locked}><div className={styles.lockGlow}/><LockKeyhole size={42}/><span>EXPERIENCIA EXCLUSIVA DIAMANTE</span><h1>Tu espacio ritual te espera</h1><p>Cuando alcances el Rango Diamante podrás seguir el estado, las fases y la evolución visual de tus rituales desde este espacio privado.</p><div className={styles.preview}><b>Estado del ritual</b><i/><b>Progreso y fases</b><i/><b>Consejo para este momento</b></div><small>Tu rango actual: {rank||"Sin rango"}</small></section>}
function Empty(){return <section className={styles.empty}><Sparkles size={45}/><span>RANGO DIAMANTE</span><h1>Tu espacio ritual está preparado</h1><p>Cuando tengas un ritual activo podrás seguir aquí cada etapa de su evolución.</p></section>}
function Active({ritual,history}:{ritual:any,history:any[]}){const type=ritual.ritual_types||{},phase=ritual.phase||{},p=Number(ritual.progress||0);return <><section className={styles.hero} data-theme={type.slug}><div className={styles.eyebrow}>TU RITUAL ACTIVO · DIAMANTE</div><h1>{ritual.nombre_personalizado||type.nombre}</h1><div className={styles.status}>{ritual.estado==="pausado"?"Pausado":p>=100?"Completado":"En proceso"}</div><Visual slug={type.slug||"prosperidad"} progress={p} asset={phase.asset_url}/><div className={styles.progressHead}><b>Estado de tu ritual</b><strong>{p.toFixed(0)}%</strong></div><div className={styles.progress}><span style={{width:`${p}%`}}/></div><div className={styles.phase}>Fase {Number(phase.index||0)+1} · <b>{phase.name||"Proceso activo"}</b></div></section><section className={styles.infoGrid}><article><span>✨ HOY EN TU RITUAL</span><h2>{phase.name||"Proceso activo"}</h2><p>{ritual.message}</p></article><article className={styles.advice}><span>✦ CONSEJO PARA ESTE MOMENTO</span><p>{ritual.advice}</p></article></section><Timeline phases={type.fases||[]} current={Number(phase.index||0)}/>{history.length?<section className={styles.history}><h2>Mis rituales</h2>{history.map(h=><div key={h.id}><b>{h.ritual_types?.nombre||"Ritual"}</b><span>{h.estado} · {new Date(h.fecha_fin_real||h.created_at).toLocaleDateString("es-ES")}</span></div>)}</section>:null}</>}
function Timeline({phases,current}:{phases:any[],current:number}){return <section className={styles.timeline}><h2>El camino de tu ritual</h2><div>{phases.map((p,i)=><article key={`${p.name}-${i}`} data-state={i<current?"done":i===current?"active":"next"}><span>{i<current?"✓":String(i+1).padStart(2,"0")}</span><b>{p.name}</b></article>)}</div></section>}
