"use client";
import { useEffect,useState } from "react";
import { Star } from "lucide-react";
import ClienteLayout from "@/components/cliente/ClienteLayout";
import { supabaseBrowser } from "@/lib/supabase-browser";
import styles from "./Reviews.module.css";
const sb=supabaseBrowser();
type T={id:string;nombre:string;average:number;count:number;mine:any;reviews:any[]};
export default function ReviewsPage(){const [items,setItems]=useState<T[]>([]);const [drafts,setDrafts]=useState<Record<string,{rating:number;comment:string}>>({});const [msg,setMsg]=useState("");const [saving,setSaving]=useState("");
async function token(){return (await sb.auth.getSession()).data.session?.access_token||""} async function load(){const t=await token();if(!t){location.href="/cliente/login";return}const r=await fetch("/api/cliente/resenas",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});const j=await r.json();if(j.ok){setItems(j.tarotistas);const d:any={};j.tarotistas.forEach((x:T)=>d[x.id]={rating:Number(x.mine?.rating||0),comment:String(x.mine?.comment||"")});setDrafts(d)}else setMsg(j.error)} useEffect(()=>{void load()},[]);
async function save(x:T){const d=drafts[x.id];if(!d?.rating){setMsg("Selecciona de 1 a 5 estrellas.");return}setSaving(x.id);setMsg("");const t=await token();const r=await fetch("/api/cliente/resenas",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({workerId:x.id,rating:d.rating,comment:d.comment})});const j=await r.json();setSaving("");if(!j.ok){setMsg(j.error||"No se pudo guardar la reseña.");return}setMsg("Reseña guardada correctamente.");await load()}
return <ClienteLayout title="Reseñas" subtitle="Comparte tu experiencia real con nuestras tarotistas."><section className="tc-card" style={{padding:22}}><div className="tc-panel-title">Reputación Celestial</div><p className="tc-muted">Puntúa de 1 a 5 estrellas. Puedes editar tu propia reseña; nunca se crea una segunda para la misma tarotista.</p>{msg?<div className="tc-chip" style={{marginBottom:16}}>{msg}</div>:null}<div className={styles.grid}>{items.map(x=>{const d=drafts[x.id]||{rating:0,comment:""};return <article className={styles.card} key={x.id}><div className={styles.top}><div className={styles.avatar}>{x.nombre.slice(0,1).toUpperCase()}</div><div><h2>{x.nombre}</h2><div className={styles.score}>{x.count?`${x.average.toFixed(1)} / 5 · ${x.count} reseña${x.count===1?"":"s"}`:"Sin reseñas todavía"}</div></div></div><div className={styles.stars}>{[1,2,3,4,5].map(n=><button aria-label={`${n} estrellas`} key={n} className={n<=d.rating?styles.starOn:styles.star} onClick={()=>setDrafts(v=>({...v,[x.id]:{...d,rating:n}}))}>★</button>)}</div><textarea className={`tc-input tc-textarea ${styles.textarea}`} maxLength={500} value={d.comment} onChange={e=>setDrafts(v=>({...v,[x.id]:{...d,comment:e.target.value}}))} placeholder={`¿Cómo fue tu experiencia con ${x.nombre}?`}/><div className={styles.actions}><button className="tc-btn tc-btn-gold" disabled={saving===x.id} onClick={()=>save(x)}>{saving===x.id?"Guardando…":x.mine?"Actualizar reseña":"Publicar reseña"}</button></div>{x.reviews.length?x.reviews.slice(0,3).map(r=><div className={styles.review} key={r.id}><strong>{"★".repeat(r.rating)}{r.isMine?" · Tu reseña":""}</strong>{r.comment?<p>{r.comment}</p>:null}</div>):<div className={styles.empty}>Sé la primera persona en dejar una reseña.</div>}</article>})}</div></section></ClienteLayout>}
