'use client';
import { useCallback, useEffect, useRef, useState, type CSSProperties, type FormEvent } from 'react';
import { ArrowUp, Bell, BookOpen, Check, ChevronRight, Clock3, Home, ListTodo, MessageCircle, Minus, RefreshCw, Settings2, Sparkles, Trash2, X } from 'lucide-react';
import { supabaseBrowser } from '@/lib/supabase-browser';
import { ASSISTANT_SECTIONS, DEFAULT_PREFERENCES, PETS, safeTab, validUuid, type AssistantCard, type AssistantMemory, type AssistantResult, type AssistantTask, type PetId, type PetState, type Preferences } from '@/lib/central-assistant';
import CompanionCharacter from './CompanionCharacter';
import { useCompanionInitiative } from './useCompanionInitiative';
import { useCompanionMotion } from './useCompanionMotion';
import styles from './CentralCompanion.module.css';

type Pane = 'chat'|'brief'|'tasks'|'memory'|'settings';
type Entry = { question:string; result:AssistantResult };
export default function CentralCompanion({ tab, workerId, onNavigate }: { tab:string; workerId?:string|null; onNavigate:(tab:string,clientId?:string)=>void }) {
  const [pet,setPet]=useState<PetId>('draco'),[preferences,setPreferences]=useState<Preferences>(DEFAULT_PREFERENCES),[open,setOpen]=useState(false),[pane,setPane]=useState<Pane>('chat');
  const [ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState('guided'),[name,setName]=useState(''),[scheduler,setScheduler]=useState(false);
  const [messages,setMessages]=useState<Entry[]>([]),[summary,setSummary]=useState<AssistantResult|null>(null),[tasks,setTasks]=useState<AssistantTask[]>([]),[memories,setMemories]=useState<AssistantMemory[]>([]);
  const [question,setQuestion]=useState(''),[bubble,setBubble]=useState(''),[sleeping,setSleeping]=useState(false),[celebrate,setCelebrate]=useState(false),[reduced,setReduced]=useState(false),[mini,setMini]=useState(false);
  const [memoryEdit,setMemoryEdit]=useState<AssistantMemory|null>(null),[topic,setTopic]=useState(''),[content,setContent]=useState(''),[taskTitle,setTaskTitle]=useState(''),[taskKind,setTaskKind]=useState('reminder'),[taskDue,setTaskDue]=useState(''),[recurrence,setRecurrence]=useState('none');
  const [resting,setResting]=useState(false),[proposalStates,setProposalStates]=useState<Record<string,string>>({});
  const button=useRef<HTMLButtonElement>(null),panel=useRef<HTMLElement>(null),input=useRef<HTMLTextAreaElement>(null),epoch=useRef(0),alive=useRef(true),lastActivity=useRef(Date.now()),bubbleTimer=useRef<ReturnType<typeof setTimeout>>(),requestController=useRef<AbortController|null>(null);
  const motion=useCompanionMotion(preferences.motion&&!reduced&&!mini,open||busy);
  const say=useCallback((text:string)=>{setBubble(text);clearTimeout(bubbleTimer.current);bubbleTimer.current=setTimeout(()=>setBubble(''),18000);},[]);
  const initiative=useCompanionInitiative({ready,open,busy,mini,tab,pet,workerId,preferences,bubble,say});
  const api=useCallback(async(body?:unknown)=>{
    const current=epoch.current; const session=(await supabaseBrowser().auth.getSession()).data.session;
    if(!session)throw new Error('Inicia sesión para hablar con tu compañero.');
    const response=await fetch('/api/central/assistant',{method:body?'POST':'GET',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(115000)});
    const data=await response.json();if(!alive.current||current!==epoch.current)throw new Error('La sesión cambió.');if(!response.ok||!data.ok)throw new Error(data.error||'No pude completar la petición.');return data;
  },[]);
  const load=useCallback(async()=>{
    const data=await api();setPet(data.profile?.pet==='sol'?'sol':'draco');setPreferences(data.preferences);setName(data.worker.name);setTasks(data.tasks);setMemories(data.memories);setMode(data.mode);setScheduler(data.schedulerConfigured);setMessages(data.history.map((h:any)=>({question:h.question,result:h.result})));setReady(true);
  },[api]);
  useEffect(()=>{
    alive.current=true;epoch.current++;setReady(false);setProposalStates({});setMemoryEdit(null);setTopic('');setContent('');setMessages([]);setSummary(null);setTasks([]);setMemories([]);setBubble('');setOpen(false);setError('');
    const effectEpoch=epoch.current;
    load().then(async()=>{const b=await api({action:'brief'});if(b.delivered){setSummary(b.result);say('Tu resumen de hoy está preparado. ¿Lo revisamos?');}}).catch(e=>{if(alive.current&&effectEpoch===epoch.current)setError(e.message);});
    const auth=supabaseBrowser().auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){epoch.current++;setReady(false);setMessages([]);setTasks([]);setMemories([]);setSummary(null);setOpen(false);setBubble('');}});
    return()=>{alive.current=false;epoch.current++;auth.data.subscription.unsubscribe();clearTimeout(bubbleTimer.current);requestController.current?.abort();};
  },[workerId,load,api,say]);
  useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
  useEffect(()=>{
    const active=()=>{lastActivity.current=Date.now();setSleeping(false);setResting(false);};window.addEventListener('pointerdown',active);window.addEventListener('keydown',active);
    const timer=setInterval(()=>{
      if(document.hidden||open||busy||!ready)return;
      const idle=Date.now()-lastActivity.current;setSleeping(idle>90000);
      setResting(preferences.humor&&idle>180000&&idle<300000&&!!summary&&!summary.unavailable?.length&&!summary.cards.some(c=>c.priority==='attention'));
    },15000);return()=>{clearInterval(timer);window.removeEventListener('pointerdown',active);window.removeEventListener('keydown',active);};
  },[open,busy,ready,preferences.humor,preferences.proactive,pet,say,summary]);
  useEffect(()=>{
    if(!ready||!preferences.proactive)return;
    const interval=setInterval(()=>{if(document.hidden||busy)return;api().then(data=>{setTasks(data.tasks);setMemories(data.memories);}).catch(()=>{});},90000);return()=>clearInterval(interval);
  },[api,ready,preferences.proactive,busy]);
  useEffect(()=>{
    if(!ready||!preferences.proactive)return;
    const timer=setInterval(()=>{if(document.hidden||busy||open)return;api({action:'monitor'}).then(data=>{if(data.result)setSummary(data.result);if(data.notice)say(`${data.notice.title}. ${data.notice.detail}`);}).catch(()=>{});},300000);
    return()=>clearInterval(timer);
  },[api,ready,preferences.proactive,busy,open,say]);
  useEffect(()=>{
    if(!ready||!preferences.motion||reduced||open||busy||mini)return;
    const timer=setInterval(()=>{if(document.hidden||Date.now()-lastActivity.current<20000||document.querySelector('[role="dialog"]'))return;const anchors=[...document.querySelectorAll<HTMLElement>('main h2,main h3,[data-companion-landmark]')].filter(el=>{const r=el.getBoundingClientRect();return r.top>90&&r.bottom<window.innerHeight-160;});if(anchors.length)motion.point(anchors[Math.floor(Math.random()*anchors.length)]);},45000);
    return()=>clearInterval(timer);
  },[ready,preferences.motion,reduced,open,busy,mini,motion.point]);
  useEffect(()=>{
    if(!ready||open||!preferences.motion||reduced)return;
    const timer=setTimeout(()=>{const el=document.querySelector<HTMLElement>(`[data-companion-nav="${safeTab(tab)?tab:'central'}"]`);motion.point(el);},450);
    return()=>clearTimeout(timer);
  },[tab,ready,open,preferences.motion,reduced,motion.point]);
  useEffect(()=>{if(open){setBubble('');setMini(false);setTimeout(()=>{if(pane==='chat')input.current?.focus();else panel.current?.focus();},40);} },[open,pane]);
  const close=()=>{setOpen(false);button.current?.focus();};
  const perform=async(body:unknown,refresh=true)=>{setBusy(true);setError('');try{const result=await api(body);if(refresh)await load();return result;}catch(e){setError(e instanceof Error?e.message:'No pude completar la petición.');return null;}finally{setBusy(false);}};
  const ask=async(text:string,query?:unknown)=>{if(!text.trim()||busy)return;setQuestion('');const result=await perform(query?{action:'query',query,requestId:crypto.randomUUID()}:{action:'chat',question:text,tab,requestId:crypto.randomUUID()},false);if(result){setMessages(m=>[...m,{question:text,result:result.result}]);setCelebrate(true);setTimeout(()=>setCelebrate(false),2200);}};
  const refreshBrief=async()=>{const b=await perform({action:'brief',manual:true},false);if(b)setSummary(b.result);};
  const navigate=(card:AssistantCard)=>{if(!safeTab(card.tab)||(card.clientId&&!validUuid(card.clientId)))return;setOpen(false);onNavigate(card.tab,card.clientId);say(card.detail);};
  const alert=async(card:AssistantCard,operation:string)=>{const r=await perform({action:'alert',key:card.id,operation},false);if(r)setSummary(s=>s?{...s,cards:s.cards.filter(c=>c.id!==card.id)}:s);};
  const state:PetState=busy?'thinking':error&&open?'error':motion.moving?'walking':celebrate?'celebrating':motion.highlight?'pointing':resting?'break':sleeping?'sleeping':open?'listening':'idle';
  const renderProposal=(result:AssistantResult)=>{
    const proposal=result.proposal;if(!proposal)return null;const key=JSON.stringify(proposal),status=proposalStates[key];
    return <article className={styles.card}><strong>{proposal.type==='memory'?'Guardar recuerdo':'Programar tarea'}</strong><p>{proposal.type==='memory'?`${proposal.topic}: ${proposal.content}`:`${proposal.title} · ${new Date(proposal.due_at).toLocaleString('es-ES',{timeZone:'Europe/Madrid'})} Madrid · ${proposal.recurrence==='none'?'Una vez':proposal.recurrence==='daily'?'Cada día':'Cada semana'}`}</p>{status?<p>{status}</p>:<div className={styles.cardActions}><button disabled={busy} onClick={()=>void perform(proposal.type==='memory'?{action:'memory_save',topic:proposal.topic,content:proposal.content}:{action:'task_create',requestId:proposal.operationId||crypto.randomUUID(),...proposal}).then(r=>{if(r)setProposalStates(s=>({...s,[key]:'Guardado correctamente.'}));})}>Confirmar y guardar</button><button onClick={()=>setProposalStates(s=>({...s,[key]:'Propuesta cancelada. No se guardó nada.'}))}>Cancelar</button></div>}</article>;
  };
  const renderCards=(result:AssistantResult,alerts=false)=><><p className={styles.resultText}>{result.text}</p>{result.unavailable?.length?<p className={styles.notice}>Fuentes pendientes: {result.unavailable.join(', ')}</p>:null}<div className={styles.cards}>{result.cards.map(card=><article key={card.id} className={styles.card} data-priority={card.priority}><div className={styles.cardHeading}><span className={styles.dot}/><strong>{card.title}</strong></div><p>{card.detail}</p>{card.date&&<small>{new Date(card.date).toLocaleString('es-ES',{timeZone:'Europe/Madrid'})}</small>}<div className={styles.cardActions}><button onClick={()=>navigate(card)}>Abrir {ASSISTANT_SECTIONS[card.tab]?.label||'panel'} <ChevronRight size={13}/></button>{alerts&&<><button onClick={()=>void alert(card,'snooze')} disabled={busy} title="Posponer una hora"><Clock3 size={14}/></button><button onClick={()=>void alert(card,'dismiss')} disabled={busy} title="Ocultar este aviso; no resuelve la incidencia"><Check size={14}/></button></>}</div><small>{card.source}</small></article>)}</div>{result.pages&&result.pages>1&&<div className={styles.pagination}><button disabled={busy||(result.page||1)<=1} onClick={()=>void ask('Página anterior',{...result.query,page:(result.page||1)-1})}>Anterior</button><span>{result.page} / {result.pages}</span><button disabled={busy||(result.page||1)>=result.pages} onClick={()=>void ask('Página siguiente',{...result.query,page:(result.page||1)+1})}>Siguiente</button></div>}<small className={styles.timestamp}>Consultado {new Date(result.updatedAt).toLocaleTimeString('es-ES',{timeZone:'Europe/Madrid'})} · Madrid</small></>;
  const saveTask=(event:FormEvent)=>{event.preventDefault();void perform({action:'task_create',requestId:crypto.randomUUID(),title:taskTitle,kind:taskKind,due_at:new Date(taskDue).toISOString(),recurrence,days:30}).then(r=>{if(r){setTaskTitle('');setTaskDue('');say('Tarea guardada. Puedes seguir su estado aquí.');}});};
  return <div data-companion-root className={styles.root} style={{'--pet-accent':PETS[pet].accent} as CSSProperties}>
    {motion.highlight&&!open&&<div className={styles.highlight} style={{left:motion.highlight.left-4,top:motion.highlight.top-4,width:motion.highlight.width+8,height:motion.highlight.height+8}}/>}
    <div ref={motion.ref} className={styles.traveller} data-moving={motion.moving}>
      {bubble&&!open&&<div className={styles.bubble} role="status"><p>{bubble}</p><div className={styles.bubbleActions}><button onClick={()=>{if(bubble.includes('recuerde')){setPane('memory');setOpen(true);return;}setPane('chat');setOpen(true);void ask(['mis-clientas','crm','recuperar-clientes','captacion'].includes(tab)?'Clientes sin llamar en 30 días':tab.includes('xp')||tab==='tienda'?'Explícame mi XP':'Mi resumen de hoy');}}>Sí, ayúdame</button><button onClick={initiative.hush}>Ahora no · 10 min</button></div></div>}
      <button ref={button} className={`${styles.petButton} ${mini?styles.mini:''}`} onClick={()=>setOpen(o=>!o)} aria-label={`Abrir ${PETS[pet].name}, tu compañero`} aria-expanded={open} aria-controls="central-companion-panel"><CompanionCharacter pet={pet} state={state} gesture={busy||motion.moving?undefined:initiative.gesture} reduced={reduced||!preferences.motion}/><span className={styles.nameTag}><i/>{PETS[pet].name}<MessageCircle size={12}/></span></button>
      {!open&&<div className={styles.petTools}><button title="Saludar y animarse" aria-label="Saludar y animarse" onClick={initiative.entertain}><Sparkles size={12}/></button><button title="Volver a su rincón" onClick={motion.dock}><Home size={12}/></button><button title={mini?'Ampliar mascota':'Minimizar mascota'} onClick={()=>setMini(m=>!m)}><Minus size={12}/></button></div>}
    </div>
    {open&&<section id="central-companion-panel" ref={panel} tabIndex={-1} className={styles.panel} role="dialog" aria-label={`Asistente ${PETS[pet].name}`} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close();}}}>
      <header className={styles.header}><div className={styles.avatar}><CompanionCharacter pet={pet} state={state} gesture={busy||motion.moving?undefined:initiative.gesture} reduced={reduced||!preferences.motion}/></div><div><div className={styles.eyebrow}>TU COMPAÑERO CELESTIAL</div><h2>{PETS[pet].name} <span>✦</span></h2><p>{PETS[pet].description}</p></div><button className={styles.close} onClick={close} aria-label="Cerrar asistente"><X size={18}/></button></header>
      <div className={styles.context}><span className={styles.liveDot}/>{ASSISTANT_SECTIONS[tab]?.label||'Tu panel'}<span>{mode==='ai'?'Conversación IA':'Consultas guiadas'}</span></div>
      <nav className={styles.tabs} aria-label="Herramientas del compañero">{([['chat','Conversar',MessageCircle],['brief','Mi turno',Bell],['tasks','Tareas',ListTodo],['memory','Memoria',BookOpen],['settings','Ajustes',Settings2]] as const).map(([key,label,Icon])=><button key={key} aria-current={pane===key?'page':undefined} onClick={()=>setPane(key)}><Icon size={16}/><span>{label}</span></button>)}</nav>
      {error&&<div role="alert" className={styles.error}>{error}<button onClick={()=>void perform(undefined)} disabled={busy}>Reintentar</button></div>}
      <div className={styles.content}>
      {!ready&&!error&&<p>Preparando tu compañero…</p>}
      {pane==='chat'&&<><div className={styles.welcome}><span>✦</span><h3>{name?`Hola, ${name.split(' ')[0]}`:'Estoy aquí para ayudarte'}</h3><p>{ASSISTANT_SECTIONS[tab]?.help||ASSISTANT_SECTIONS.central.help}</p></div><div className={styles.quickActions}>{['Mi resumen de hoy','Clientes sin llamar en 30 días','Clientes con +34','Explícame mi XP'].map(q=><button key={q} disabled={busy||!ready} onClick={()=>void ask(q)}>{q}<ChevronRight size={14}/></button>)}</div><div aria-live="polite" aria-busy={busy}>{messages.map((m,i)=><div className={styles.exchange} key={i}><p className={styles.question}>{m.question}</p><div className={styles.answer}><span className={styles.answerName}>✦ {PETS[pet].name}</span>{renderCards(m.result)}{renderProposal(m.result)}</div></div>)}{busy&&<p className={styles.working}>Consultando tus datos<span>•••</span></p>}</div></>}
      {pane==='brief'&&<><div className={styles.sectionTitle}><div><h3>Tu turno, en perspectiva</h3><p>Resumen al primer acceso del día · Madrid</p></div><button disabled={busy||!ready} onClick={()=>void refreshBrief()} aria-label="Actualizar resumen"><RefreshCw size={16}/></button></div>{summary?renderCards(summary,true):<div className={styles.empty}><Sparkles/><p>Prepara tu resumen de pendientes, novedades y oportunidades.</p><button className={styles.primary} disabled={busy||!ready} onClick={()=>void refreshBrief()}>Ver mi resumen</button></div>}</>}
      {pane==='tasks'&&<><div className={styles.sectionTitle}><div><h3>Déjamelo apuntado</h3><p>Recordatorios y análisis programados</p></div></div><p className={styles.notice}>{scheduler?"Clave del planificador configurada. La ejecución automática necesita también un servicio que invoque el servidor; comprueba el estado de tus tareas.":"Las tareas se guardan. Falta configurar el planificador del servidor para ejecutarlas automáticamente."}</p><form className={styles.form} onSubmit={saveTask}><label>Tarea<input required maxLength={200} value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="Revisar el tiempo pendiente de Luna"/></label><label>Qué hacer<select value={taskKind} onChange={e=>setTaskKind(e.target.value)}><option value="reminder">Recordármelo</option><option value="inactive">Buscar clientes inactivos · 30 días</option><option value="opportunities">Preparar oportunidades · 30 días</option></select></label><div className={styles.formRow}><label>Cuándo · hora de tu dispositivo<input required type="datetime-local" value={taskDue} onChange={e=>setTaskDue(e.target.value)}/></label><label>Repetir<select value={recurrence} onChange={e=>setRecurrence(e.target.value)}><option value="none">Una vez</option><option value="daily">Cada día</option><option value="weekly">Cada semana</option></select></label></div><button className={styles.primary} disabled={busy||!ready}>Guardar tarea</button></form><div className={styles.cards}>{tasks.map(t=><article className={styles.card} key={t.id}><strong>{t.title}</strong><p>{({scheduled:'Programada',running:'En curso',completed:'Completada',failed:'Necesita revisión',cancelled:'Cancelada',awaiting_input:'Espera información'} as any)[t.status]||t.status} · {new Date(t.due_at).toLocaleString('es-ES',{timeZone:'Europe/Madrid'})} Madrid</p>{t.last_error&&<p className={styles.notice}>{t.last_error}</p>}{t.result&&<details><summary>Ver último resultado</summary>{renderCards(t.result)}</details>}<div className={styles.cardActions}>{!['completed','cancelled'].includes(t.status)&&<button disabled={busy} onClick={()=>void perform({action:'task_cancel',id:t.id})}>Cancelar</button>}<button disabled={busy} onClick={()=>void perform({action:'task_reschedule',id:t.id,due_at:new Date(Date.now()+86400000).toISOString()})}>Reprogramar en 24 h</button></div></article>)}</div></>}
      {pane==='memory'&&<><div className={styles.sectionTitle}><div><h3>Lo que recuerdo de ti</h3><p>Instrucciones privadas, editables y bajo tu control</p></div></div><form className={styles.form} onSubmit={e=>{e.preventDefault();void perform({action:'memory_save',id:memoryEdit?.id,topic,content,replace:!!memoryEdit}).then(r=>{if(r){setMemoryEdit(null);setTopic('');setContent('');}});}}><label>Tema<input required maxLength={80} disabled={!!memoryEdit} value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Cómo prefiero los resúmenes"/></label><label>Indicación<textarea required maxLength={1000} value={content} onChange={e=>setContent(e.target.value)} placeholder="Empieza siempre por las incidencias pendientes."/></label><button className={styles.primary} disabled={busy||!ready}>{memoryEdit?'Actualizar recuerdo':'Guardar recuerdo'}</button>{memoryEdit&&<button type="button" onClick={()=>{setMemoryEdit(null);setTopic('');setContent('');}}>Cancelar edición</button>}</form><div className={styles.cards}>{memories.map(m=><article className={styles.card} key={m.id}><strong>{m.topic}</strong><p>{m.content}</p><small>Indicación explícita · {new Date(m.updated_at).toLocaleDateString('es-ES')}</small><div className={styles.cardActions}><button onClick={()=>{setMemoryEdit(m);setTopic(m.topic);setContent(m.content);}}>Editar</button><button disabled={busy} onClick={()=>void perform({action:'memory_delete',id:m.id})}><Trash2 size={13}/> Borrar</button></div></article>)}</div></>}
      {pane==='settings'&&<><h3>A tu manera</h3><p className={styles.subtle}>Tú decides cómo te acompaño.</p>{([['motion','Movimiento y desplazamientos'],['humor','Humor y escenas de descanso'],['proactive','Avisos y conversación espontánea'],['sound','Voz en español (opcional)']] as const).map(([key,label])=><label className={styles.toggle} key={key}><span>{label}</span><input type="checkbox" checked={preferences[key]} disabled={busy} onChange={e=>void perform({action:'preferences',preferences:{[key]:e.target.checked}})}/></label>)}{reduced&&<p className={styles.notice}>Tu dispositivo solicita movimiento reducido. Las animaciones están pausadas.</p>}<p className={styles.subtle}>La voz utiliza las voces disponibles en tu navegador y se activa tras interactuar con el panel. {mode==='guided'?'La conversación IA requiere configurar el modelo y su credencial en el servidor. Las consultas rápidas usan datos reales.':'Las respuestas utilizan herramientas con tus permisos.'}</p><button className={styles.secondary} disabled={busy} onClick={()=>void perform({action:'history_delete'})}>Borrar historial de conversación</button><p className={styles.subtle}>El historial se conserva hasta 30 días cuando el mantenimiento programado está activo. Borrarlo no elimina tus tareas ni recuerdos.</p></>}
      </div>
      {pane==='chat'&&<form className={styles.composer} onSubmit={e=>{e.preventDefault();void ask(question);}}><textarea ref={input} value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} placeholder={`Pregúntale a ${PETS[pet].name}…`} aria-label="Mensaje para tu compañero" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask(question);}}}/><button disabled={busy||!ready||!question.trim()} aria-label="Enviar mensaje"><ArrowUp size={19}/></button><small>Datos de tu cartera · Acciones bajo tu control</small></form>}
    </section>}
  </div>;
}


