'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { supabaseBrowser } from '@/lib/supabase-browser';
export default function CompanionAssignments() {
  const [knowledge,setKnowledge]=useState<any[]>([]),[topic,setTopic]=useState(''),[content,setContent]=useState('');
  const [workers,setWorkers] = useState<any[]>([]), [profiles,setProfiles] = useState<Record<string,string>>({}), [notice,setNotice] = useState(''), [busy,setBusy] = useState(false);
  async function request(body?: unknown) {
    const session = (await supabaseBrowser().auth.getSession()).data.session;
    const response = await fetch('/api/admin/companions', { method: body ? 'POST' : 'GET', headers: { Authorization: `Bearer ${session?.access_token || ''}`, 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined });
    const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || 'Necesitas una sesión de administrador.'); return data;
  }
  useEffect(() => { request().then(d => { setWorkers(d.workers); setKnowledge(d.knowledge); setProfiles(Object.fromEntries(d.profiles.map((p:any) => [p.worker_id,p.pet]))); }).catch(e => setNotice(e.message)); }, []);
  return <main style={{ maxWidth: 850, margin: '50px auto', padding: 24 }} className="tc-card"><Link href="/admin">← Volver a administración</Link><h1>Compañeros de centrales</h1><p>Asigna Sol a María y Draco a Michael seleccionando sus cuentas. La relación se guarda por identificador de trabajador.</p><p role="status">{notice}</p>{workers.map(w => <div key={w.id} style={{ display:'flex',alignItems:'center',gap:16,margin:'20px 0',flexWrap:'wrap' }}><div style={{ flex:1 }}><strong>{w.display_name}</strong><br/><small>{w.id}</small></div><select aria-label={`Mascota de ${w.display_name}`} value={profiles[w.id] || 'draco'} onChange={e => setProfiles(p => ({ ...p,[w.id]:e.target.value }))}><option value="sol">Sol · espíritu de fuego</option><option value="draco">Draco · dragón celestial</option></select><button className="tc-btn" disabled={busy} onClick={async()=>{setBusy(true);try{await request({worker_id:w.id,pet:profiles[w.id]||'draco'});setNotice(`Asignación guardada para ${w.display_name}.`);}catch(e){setNotice(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}}>Guardar</button></div>)}<section style={{marginTop:40}}><h2>Conocimiento aprobado</h2><p>Documenta procesos para ambas mascotas. Cada publicación conserva una versión anterior.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await request({action:"knowledge",topic,content});const d=await request();setKnowledge(d.knowledge);setNotice("Conocimiento publicado.");setTopic("");setContent("");}catch(e){setNotice(e instanceof Error?e.message:"No se pudo publicar.");}finally{setBusy(false);}}}><label>Tema<input required maxLength={80} value={topic} onChange={e=>setTopic(e.target.value)} style={{display:"block",width:"100%",margin:"10px 0"}}/></label><label>Proceso o indicación<textarea required maxLength={4000} rows={7} value={content} onChange={e=>setContent(e.target.value)} style={{display:"block",width:"100%",margin:"10px 0"}}/></label><button className="tc-btn" disabled={busy||!topic.trim()||!content.trim()}>Publicar versión aprobada</button></form>{knowledge.map((k:any)=><details key={`${k.topic}:${k.version}`} style={{marginTop:16}}><summary>{k.topic} · versión {k.version}</summary><p style={{whiteSpace:"pre-wrap"}}>{k.content}</p><button onClick={()=>{setTopic(k.topic);setContent(k.content);}}>Preparar actualización</button></details>)}</section></main>;
}

