"use client";
import { useCallback, useEffect, useState } from "react";
import { BadgeCheck, Eye, EyeOff, Trash2 } from "lucide-react";
import { supabaseBrowser } from "@/lib/supabase-browser";

const sb=supabaseBrowser();
export default function CentralReviewsAdminPanel(){const[rows,setRows]=useState<any[]>([]);const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const token=(await sb.auth.getSession()).data.session?.access_token||"";const response=await fetch("/api/admin/central-reviews",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const result=await response.json().catch(()=>({}));if(result.ok)setRows(result.reviews||[]);else setMessage(result.error||"No se pudieron cargar las reseñas.");setLoading(false);},[]);
 useEffect(()=>{void load();const channel=sb.channel("admin-central-reviews-live").on("postgres_changes",{event:"*",schema:"public",table:"central_review_stats"},()=>void load()).subscribe();return()=>{void sb.removeChannel(channel)}},[load]);
 async function moderate(id:string,status:string){const token=(await sb.auth.getSession()).data.session?.access_token||"";const response=await fetch("/api/admin/central-reviews",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({id,status})});const result=await response.json();setMessage(result.ok?"Moderación guardada.":result.error||"No se pudo guardar.");if(result.ok)await load();}
 return <div className="tc-card"><div className="tc-row" style={{justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div className="tc-title">⭐ Moderación de reseñas</div><div className="tc-sub" style={{marginTop:6}}>Opiniones verificadas, ocultación y eliminación administrativa. Las puntuaciones no se modifican.</div></div><button className="tc-btn" onClick={()=>void load()}>Recargar</button></div>{message&&<div className="tc-sub" style={{marginTop:10}}>{message}</div>}<div className="tc-hr"/><div style={{overflowX:"auto"}}><table className="tc-table"><thead><tr><th>Clienta</th><th>Central</th><th>Valoración</th><th>Comentario</th><th>Verificación</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.clientName}</td><td><b>{row.workerName}</b></td><td>{"★".repeat(Number(row.rating)||0)}</td><td style={{minWidth:240}}>{row.comment||"—"}</td><td>{row.verified?<span className="tc-chip"><BadgeCheck size={13}/> Real</span>:"Histórica"}</td><td><span className="tc-chip">{row.status}</span></td><td><div className="tc-row" style={{gap:6,flexWrap:"wrap"}}><button className="tc-btn" title="Publicar" onClick={()=>void moderate(row.id,"published")}><Eye size={15}/></button><button className="tc-btn" title="Ocultar" onClick={()=>void moderate(row.id,"hidden")}><EyeOff size={15}/></button><button className="tc-btn tc-btn-danger" title="Eliminar" onClick={()=>void moderate(row.id,"deleted")}><Trash2 size={15}/></button></div></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={7}>No hay reseñas todavía.</td></tr>}{loading&&<tr><td colSpan={7}>Cargando…</td></tr>}</tbody></table></div></div>;
}
