"use client";
import { useCallback, useEffect, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import styles from "./ClientRanksAdminPanel.module.css";

const sb = supabaseBrowser();
const rankLabel=(r:any)=>r?String(r).charAt(0).toUpperCase()+String(r).slice(1):"Sin rango";
const rankClass=(r:any)=>r==="oro"?styles.gold:r==="plata"?styles.silver:r==="bronce"?styles.bronze:styles.none;
const money=(n:any)=>Number(n||0).toLocaleString("es-ES",{style:"currency",currency:"EUR"});

export default function ClientRanksAdminPanel(){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [page,setPage]=useState(1),[pagination,setPagination]=useState<any>({page:1,total:0,total_pages:1});
 const [q,setQ]=useState(""),[business,setBusiness]=useState("all"),[rank,setRank]=useState(""),[assignment,setAssignment]=useState("all"),[order,setOrder]=useState("spent_desc");
 const [selected,setSelected]=useState<any>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const [form,setForm]=useState<any>({rank:"oro",intervention_type:"temporary",starts_at:new Date().toISOString().slice(0,16),ends_at:"",reason:"",notes:""});
 const token=async()=> (await sb.auth.getSession()).data.session?.access_token||"";
 const load=useCallback(async()=>{setLoading(true);setError("");try{const t=await token();const p=new URLSearchParams({page:String(page),page_size:"15",q,business,assignment,order});if(rank)p.set("rank",rank);const r=await fetch(`/api/admin/client-ranks/manage?${p}`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"ERR");setRows(j.rows||[]);setPagination(j.pagination||{});}catch(e:any){setError(e.message||"Error");}finally{setLoading(false)}},[page,q,business,rank,assignment,order]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{let timer:number|undefined;const ch=sb.channel("admin-client-ranks-live").on("postgres_changes",{event:"*",schema:"public",table:"client_rank_overrides"},()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>void load(),300)}).on("postgres_changes",{event:"*",schema:"public",table:"crm_cliente_pagos"},()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>void load(),300)}).subscribe();return()=>{if(timer)window.clearTimeout(timer);void sb.removeChannel(ch)}},[load]);
 const open=(row:any)=>{setSelected(row);setMessage("");setForm({rank:row.effective_rank||"oro",intervention_type:"temporary",starts_at:new Date().toISOString().slice(0,16),ends_at:"",reason:"",notes:""})};
 const submit=async(action="set")=>{if(!selected)return;setSaving(true);setMessage("");try{const t=await token();const body=action==="restore"?{action,client_id:selected.id}:{action:"set",client_id:selected.id,rank:form.rank,intervention_type:form.intervention_type,starts_at:new Date(form.starts_at).toISOString(),ends_at:form.intervention_type==="permanent"?null:(form.ends_at?new Date(form.ends_at).toISOString():null),reason:form.reason,notes:form.notes};const r=await fetch("/api/admin/client-ranks/manage",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"ERR");setSelected(null);await load()}catch(e:any){setMessage(e.message||"No se pudo guardar")}finally{setSaving(false)}};
 return <section className={styles.root}>
  <div className={styles.toolbar}><input value={q} onChange={e=>{setPage(1);setQ(e.target.value)}} placeholder="Buscar nombre, teléfono o correo"/><select value={business} onChange={e=>{setPage(1);setBusiness(e.target.value)}}><option value="all">Todos los negocios</option><option value="celestial">Celestial</option><option value="orion">Orion</option><option value="flowly">Flowly</option><option value="leonaris">Leonaris</option></select><select value={rank} onChange={e=>{setPage(1);setRank(e.target.value)}}><option value="">Todos los rangos</option><option value="bronce">Bronce</option><option value="plata">Plata</option><option value="oro">Oro</option></select><select value={assignment} onChange={e=>{setPage(1);setAssignment(e.target.value)}}><option value="all">Automático y manual</option><option value="automatic">Solo automático</option><option value="manual">Con intervención</option></select><select value={order} onChange={e=>setOrder(e.target.value)}><option value="spent_desc">Mayor gasto</option><option value="spent_asc">Menor gasto</option><option value="name">Nombre</option></select></div>
  <div className={styles.panel}>{loading?<div className={styles.state}>Cargando rangos reales…</div>:error?<div className={`${styles.state} ${styles.error}`}>{error}</div>:<><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Clienta</th><th>Negocio</th><th>Automático</th><th>Efectivo</th><th>Gasto / compras</th><th>Progreso</th><th>Intervención</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className={styles.client}><strong>{row.name}</strong><small>{row.phone||"Sin teléfono"}{row.email?` · ${row.email}`:""}</small></td><td>{rankLabel(row.business)}</td><td><span className={`${styles.rank} ${rankClass(row.automatic_rank)}`}>{rankLabel(row.automatic_rank)}</span></td><td><span className={`${styles.rank} ${rankClass(row.effective_rank)}`}>{rankLabel(row.effective_rank)}</span></td><td><strong>{money(row.spent_30d)}</strong><div className={styles.muted}>{row.purchases_30d} compras</div></td><td><div className={styles.progress}><span style={{width:`${row.progress}%`}}/></div><div className={styles.muted}>{row.next_rank?`Hacia ${rankLabel(row.next_rank)}`:"Rango máximo"}</div></td><td>{row.override?<div className={styles.override}><b>{row.override.intervention_type}</b><span>{row.override.reason}</span><small>{row.override.ends_at?`Hasta ${new Date(row.override.ends_at).toLocaleDateString("es-ES")}`:"Sin vencimiento"}</small></div>:<span className={styles.muted}>Cálculo automático</span>}</td><td><button className={styles.manage} onClick={()=>open(row)}>Gestionar</button></td></tr>)}</tbody></table></div><div className={styles.footer}><span>{pagination.total||0} clientas · Página {pagination.page||1} de {pagination.total_pages||1}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Anterior</button> <button disabled={page>=(pagination.total_pages||1)} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div></div></>}</div>
  {selected?<div className={styles.modalBackdrop}><div className={styles.modal}><h2>Gestionar rango de {selected.name}</h2><div className={styles.summary}><div><span className={styles.muted}>Automático</span><strong>{rankLabel(selected.automatic_rank)}</strong></div><div><span className={styles.muted}>Efectivo</span><strong>{rankLabel(selected.effective_rank)}</strong></div></div><div className={styles.form}><label>Rango<select value={form.rank} onChange={e=>setForm({...form,rank:e.target.value})}><option value="bronce">Bronce</option><option value="plata">Plata</option><option value="oro">Oro</option></select></label><label>Intervención<select value={form.intervention_type} onChange={e=>setForm({...form,intervention_type:e.target.value})}><option value="temporary">Temporal</option><option value="penalty">Penalización temporal</option><option value="permanent">Permanente</option></select></label><label>Inicio<input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label>{form.intervention_type!=="permanent"?<label>Fin<input type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label>:null}<label className={styles.wide}>Motivo<input value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Motivo obligatorio"/></label><label className={styles.wide}>Observaciones<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{message?<p className={styles.error}>{message}</p>:null}<div className={styles.actions}>{selected.override?<button className={styles.danger} disabled={saving} onClick={()=>void submit("restore")}>Restaurar cálculo automático</button>:null}<button onClick={()=>setSelected(null)}>Cancelar</button><button className={styles.primary} disabled={saving||!form.reason||(form.intervention_type!=="permanent"&&!form.ends_at)} onClick={()=>void submit()}>{saving?"Guardando…":"Aplicar rango"}</button></div></div></div>:null}
 </section>
}
