"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import styles from "./ClientRitualsAdminPanel.module.css";
const sb=supabaseBrowser();
export default function ClientRitualsAdminPanel(){
 const [clients,setClients]=useState<any[]>([]),[types,setTypes]=useState<any[]>([]),[rituals,setRituals]=useState<any[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
 const [form,setForm]=useState<any>({cliente_id:"",ritual_type_id:"",modo:"automatico",duracion_dias:7,mensaje:"",consejo:""});
 const token=async()=> (await sb.auth.getSession()).data.session?.access_token||"";
 const load=useCallback(async()=>{setLoading(true);try{const t=await token();const r=await fetch(`/api/admin/client-rituals?q=${encodeURIComponent(q)}`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Error");setClients(j.clients||[]);setTypes(j.types||[]);setRituals(j.rituals||[]);setForm((f:any)=>({...f,ritual_type_id:f.ritual_type_id||j.types?.[0]?.id||""}));}catch(e:any){setMsg(e.message)}finally{setLoading(false)}},[q]);
 useEffect(()=>{const x=setTimeout(()=>void load(),250);return()=>clearTimeout(x)},[load]);
 useEffect(()=>{const ch=sb.channel("admin-rituals-live").on("postgres_changes",{event:"*",schema:"public",table:"client_rituals"},()=>void load()).subscribe();return()=>{void sb.removeChannel(ch)}},[load]);
 const names=useMemo(()=>new Map(clients.map(c=>[c.id,[c.nombre,c.apellido].filter(Boolean).join(" ")||c.email||c.telefono||"Cliente"])),[clients]);
 async function send(body:any){setMsg("");try{const t=await token();const r=await fetch("/api/admin/client-rituals",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"No se pudo guardar");setMsg("Guardado correctamente");await load()}catch(e:any){setMsg(e.message)}}
 return <section className={styles.root}><div className={styles.hero}><div><span>EXPERIENCIA DIAMANTE</span><h1>Rituales clientes</h1><p>Asigna y controla la evolución real de cada ritual. Supabase es la única fuente de verdad.</p></div><div className={styles.live}>● REALTIME</div></div>
 <div className={styles.grid}><div className={styles.card}><h2>Asignar nuevo ritual</h2><input placeholder="Buscar cliente…" value={q} onChange={e=>setQ(e.target.value)}/><label>Cliente<select value={form.cliente_id} onChange={e=>setForm({...form,cliente_id:e.target.value})}><option value="">Selecciona…</option>{clients.map(c=><option key={c.id} value={c.id}>{[c.nombre,c.apellido].filter(Boolean).join(" ")||c.email||c.telefono}</option>)}</select></label><label>Ritual<select value={form.ritual_type_id} onChange={e=>setForm({...form,ritual_type_id:e.target.value})}>{types.map(t=><option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label><div className={styles.two}><label>Modo<select value={form.modo} onChange={e=>setForm({...form,modo:e.target.value})}><option value="automatico">Automático</option><option value="manual">Manual</option><option value="hibrido">Híbrido</option></select></label><label>Duración (días)<input type="number" min="1" value={form.duracion_dias} onChange={e=>setForm({...form,duracion_dias:e.target.value})}/></label></div><label>Mensaje personalizado<textarea value={form.mensaje} onChange={e=>setForm({...form,mensaje:e.target.value})}/></label><label>Consejo personalizado<textarea value={form.consejo} onChange={e=>setForm({...form,consejo:e.target.value})}/></label><button disabled={!form.cliente_id||!form.ritual_type_id} onClick={()=>send({action:"create",...form})}>Iniciar ritual</button>{msg?<p className={styles.msg}>{msg}</p>:null}</div>
 <div className={styles.card}><h2>Rituales recientes</h2>{loading?<p>Cargando…</p>:rituals.length?rituals.map(r=><RitualRow key={r.id} r={r} name={names.get(r.cliente_id)||r.cliente_id} send={send}/>):<p className={styles.empty}>Todavía no hay rituales.</p>}</div></div></section>
}
function RitualRow({r,name,send}:{r:any,name:string,send:(b:any)=>void}){const [p,setP]=useState(Number(r.progreso_manual||0)),[d,setD]=useState(Math.max(1,Math.ceil((new Date(r.fecha_fin_prevista||Date.now()).getTime()-new Date(r.fecha_inicio).getTime())/86400000)));return <article className={styles.ritual}><div><strong>{name}</strong><span>{r.ritual_types?.nombre||"Ritual"} · {r.estado} · {r.modo}</span></div><div className={styles.controls}><input type="number" min="0" max="100" value={p} onChange={e=>setP(Number(e.target.value))}/><span>%</span><input type="number" min="1" value={d} onChange={e=>setD(Number(e.target.value))}/><span>días</span><button onClick={()=>send({action:"update",id:r.id,progreso:p,duracion_dias:d})}>Guardar</button>{r.estado==="activo"?<button onClick={()=>send({action:"pause",id:r.id})}>Pausar</button>:r.estado==="pausado"?<button onClick={()=>send({action:"resume",id:r.id})}>Reanudar</button>:null}<button onClick={()=>send({action:"complete",id:r.id})}>Completar</button></div></article>}
