"use client";
import { Building2, History, Plus, RefreshCw, Search, ShieldCheck, UserCheck } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import styles from "./ClientCapturesAdminPanel.module.css";

async function token(){const {data}=await supabaseBrowser().auth.getSession();return data.session?.access_token||""}
export default function ClientCapturesAdminPanel(){
 const [items,setItems]=useState<any[]>([]),[workers,setWorkers]=useState<any[]>([]);const [query,setQuery]=useState(""),[status,setStatus]=useState("all"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const response=await fetch("/api/admin/client-captures",{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"No se pudieron cargar las captaciones");setItems(payload.items||[]);setWorkers(payload.workers||[])}catch(e:any){setError(e?.message||"Error de carga")}finally{setBusy(false)}},[]);
 useEffect(()=>{void load();const sb=supabaseBrowser();const channel=sb.channel("admin-client-captures").on("postgres_changes",{event:"*",schema:"public",table:"crm_client_capture_assignments"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"crm_client_capture_audit"},()=>void load()).subscribe();return()=>{void sb.removeChannel(channel)}},[load]);
 const filtered=useMemo(()=>items.filter(item=>{const text=[item.client?.nombre,item.client?.apellido,item.client?.telefono,item.captured_by?.display_name,item.responsible?.display_name].join(" ").toLowerCase();const itemStatus=item.responsible_worker_id?"assigned":"corporate";return(!query||text.includes(query.toLowerCase()))&&(status==="all"||status===itemStatus)}),[items,query,status]);
 async function reassign(item:any,nextId:string){const next=workers.find(w=>w.id===nextId);const before=item.responsible?.display_name||"Celestial",after=next?.display_name||"Celestial";if(before===after)return;if(!window.confirm(`Mover clienta:\n${before} → ${after}\n\nEste cambio no concede XP.`))return;const reason=window.prompt("Motivo opcional de la reasignación:")||"";setBusy(true);try{const response=await fetch("/api/admin/client-captures",{method:"POST",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify({client_id:item.client_id,responsible_worker_id:nextId||null,reason})});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"No se pudo reasignar");await load()}catch(e:any){setError(e?.message||"Error de reasignación")}finally{setBusy(false)}}
 return <section className={styles.panel}>
  <header><div><span className={styles.kicker}>CENTRO DE ATRIBUCIÓN DE CARTERAS</span><h1><UserCheck/> Sistema de clientas captadas</h1><p>Captadora histórica, responsable actual y XP real permanecen separados.</p></div><button onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?styles.spin:""}/>Actualizar</button></header>
  <div className={styles.stats}><article><b>{items.filter(x=>!x.responsible_worker_id).length}</b><span>Cartera Celestial</span></article><article><b>{items.filter(x=>x.responsible_worker_id).length}</b><span>Asignadas</span></article><article><b>{items.filter(x=>x.xp_event?.status==="applied").length}</b><span>Con XP real</span></article></div>
  <div className={styles.filters}><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nombre, teléfono o responsable"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todas las carteras</option><option value="corporate">Celestial</option><option value="assigned">Centrales asignadas</option></select></div>
  <a className={styles.addWorker} href="/admin?tab=trabajadores"><Plus/> Añadir responsable desde Trabajadores</a>{error&&<div className={styles.error}>{error}</div>}
  <div className={styles.list}>{filtered.map(item=><article key={item.client_id} className={styles.card}>
   <div className={styles.identity}><strong>{[item.client?.nombre,item.client?.apellido].filter(Boolean).join(" ")||"Clienta"}</strong><span>{item.client?.telefono||"Sin teléfono"}</span><small>{item.business||item.client?.origen||"celestial"}</small></div>
   <div><span>Captada por · histórico</span><strong>{item.captured_by?.display_name||"Sin captadora confirmada"}</strong><small>{item.captured_at?new Date(item.captured_at).toLocaleString("es-ES"):"Pendiente de captación real"}</small></div>
   <div className={!item.responsible_worker_id?styles.corporate:""}><span>Responsable central</span><select value={item.responsible_worker_id||""} onChange={e=>void reassign(item,e.target.value)} disabled={busy}><option value="">✦ Celestial · Cartera corporativa</option>{workers.map(w=><option key={w.id} value={w.id}>{w.display_name} · {w.team||"Sin equipo"}</option>)}</select><small>{!item.responsible_worker_id&&<Building2/>}{item.responsible_worker_id?`${item.responsible?.team||"Central"} · Activa`:"Fuera de carteras individuales"}</small><small>{item.xp_event?.status==="applied"?`+${item.xp_event.xp_amount} XP real`:`Sin evento XP aplicado`}</small></div>
   <details><summary><History/>Historial ({item.audit?.length||0})</summary>{(item.audit||[]).map((entry:any)=><p key={entry.id}><ShieldCheck/>{entry.previous_name} → {entry.new_name}<span>{entry.reason||entry.action}</span><time>{new Date(entry.created_at).toLocaleString("es-ES")}</time></p>)}</details>
  </article>)}</div>{!busy&&!filtered.length&&<div className={styles.empty}>No hay clientas para estos filtros.</div>}
 </section>
}
