"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Award, Bolt, Coins, History, Medal, Plus, RefreshCw, Save, ShieldCheck, Sparkles, Star, Trophy, Users } from "lucide-react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import styles from "./XpSystemAdminPanel.module.css";
import AdminXpCoinConfig from "./AdminXpCoinConfig";

type Rule={action_key:string;name:string;description:string;xp_reward:number;frequency:string;enabled:boolean;integration_status:"connected"|"pending"};
type Worker={id:string;display_name:string;total_xp:number;xp_month:number;xp_today:number;level:number;level_xp:number;next_level_xp:number;clients_captured:number;repurchases:number;followups:number;consultations:number;positive_reviews:number;missions:number;coins:number|null;coins_spent:number|null;rewards_claimed:number|null;rewards_value:number|null};
const fmt=(n:any)=>Number(n||0).toLocaleString("es-ES");
export default function XpSystemAdminPanel(){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""); const [newOpen,setNewOpen]=useState(false); const [filterWorker,setFilterWorker]=useState(""); const [filterAction,setFilterAction]=useState("");
 const authFetch=useCallback(async(url:string,init?:RequestInit)=>{const {data:s}=await supabaseBrowser().auth.getSession();return fetch(url,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${s.session?.access_token||""}`,...(init?.headers||{})},cache:"no-store"});},[]);
 const load=useCallback(async()=>{setBusy(true);setError("");try{const r=await authFetch(`/api/admin/xp-system?t=${Date.now()}`);const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"No se pudo cargar");setData(j);}catch(e:any){setError(e.message)}finally{setBusy(false)}},[authFetch]); useEffect(()=>{void load()},[load]);
 async function saveRule(rule:Rule){setBusy(true);try{const r=await authFetch("/api/admin/xp-system",{method:"POST",body:JSON.stringify({op:"save_rule",...rule})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error);await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function saveExchange(config:any){setBusy(true);try{const r=await authFetch("/api/admin/xp-system",{method:"POST",body:JSON.stringify({op:"save_exchange_config",...config})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error);await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function adjust(w:Worker){const raw=prompt(`Ajustar XP de ${w.display_name}. Usa positivo o negativo:`);if(!raw)return;const amount=Number(raw);if(!Number.isFinite(amount)||!amount)return;const reason=prompt("Motivo obligatorio:")?.trim();if(!reason)return;const r=await authFetch("/api/admin/xp-system",{method:"POST",body:JSON.stringify({op:"adjust_xp",worker_id:w.id,amount,reason})});const j=await r.json();if(!r.ok||!j.ok){setError(j.error||"Error");return}await load();}
 const events=useMemo(()=> (data?.events||[]).filter((e:any)=>(!filterWorker||e.worker_id===filterWorker)&&(!filterAction||e.action_key===filterAction)),[data,filterWorker,filterAction]);
 if(!data&&!error)return <div className={styles.loading}>Cargando Sistema de XP…</div>;
 return <section className={styles.page}>
  <header className={styles.hero}><div><span><Sparkles size={14}/> PROGRESIÓN DE TELEFONISTAS</span><h1>Sistema de XP</h1><p>Centro administrativo de reglas, experiencia, niveles e historial real.</p></div><button onClick={()=>load()} disabled={busy}><RefreshCw size={16}/> Refrescar</button></header>
  {error?<div className={styles.error}>{error}</div>:null}
  <AdminXpCoinConfig value={data.coin_exchange} busy={busy} save={saveExchange}/>
  <div className={styles.metrics}>{[[Bolt,"XP este mes",fmt(data.summary.xp_month)],[Star,"XP hoy",fmt(data.summary.xp_today)],[Trophy,"Nivel medio",Number(data.summary.average_level||0).toFixed(1)],[Award,"Líder del mes",data.summary.top_worker?.name||"Sin datos"],[Coins,"Coins generadas",data.summary.coins_generated??"Sin datos"],[Medal,"Bonos reclamados",data.summary.rewards_claimed??"Sin datos"],[ShieldCheck,"Acciones activas",fmt(data.summary.active_rules)]].map(([I,l,v]:any)=><article key={l}><I size={18}/><small>{l}</small><strong>{v}</strong></article>)}</div>
  <div className={styles.sectionHead}><div><span>CONFIGURACIÓN</span><h2>Acciones que dan experiencia</h2></div><button onClick={()=>setNewOpen(true)}><Plus size={16}/> Añadir acción XP</button></div>
  <div className={styles.rules}>{(data.rules||[]).map((r:Rule)=><RuleCard key={r.action_key} rule={r} save={saveRule} busy={busy}/>)}</div>
  {newOpen?<NewRule onClose={()=>setNewOpen(false)} onSave={async(r)=>{await saveRule(r);setNewOpen(false)}}/>:null}
  <div className={styles.sectionHead}><div><span>EQUIPO REAL</span><h2>Progreso de telefonistas</h2></div></div>
  <div className={styles.workers}>{(data.workers||[]).map((w:Worker)=><article className={styles.worker} key={w.id}><div className={styles.workerTop}><div className={styles.avatar}>{String(w.display_name||"?")[0]}</div><div><small>PERFIL DE PERSONAJE</small><h3>{w.display_name}</h3></div><span>NIVEL {w.level}</span></div><div className={styles.xp}><strong>{fmt(w.level_xp)} / {fmt(w.next_level_xp)} XP</strong><div><i style={{width:`${Math.min(100,w.next_level_xp?100*w.level_xp/w.next_level_xp:0)}%`}}/></div><small>XP total · {fmt(w.total_xp)} · Este mes +{fmt(w.xp_month)} · Hoy +{fmt(w.xp_today)}</small></div><div className={styles.workerStats}><span>Clientas <b>{fmt(w.clients_captured)}</b></span><span>Recompras <b>{fmt(w.repurchases)}</b></span><span>Seguimientos <b>{fmt(w.followups)}</b></span><span>Consultas <b>{fmt(w.consultations)}</b></span><span>Coins <b>{w.coins??"Sin datos"}</b></span><span>Bonos <b>{w.rewards_claimed??"Sin datos"}</b></span></div><button className={styles.adjust} onClick={()=>adjust(w)}>Ajustar XP</button></article>)}</div>
  <div className={styles.history}><div className={styles.sectionHead}><div><span>AUDITORÍA</span><h2><History size={19}/> Historial de experiencia</h2></div><div className={styles.filters}><select value={filterWorker} onChange={e=>setFilterWorker(e.target.value)}><option value="">Telefonistas</option>{(data.workers||[]).map((w:Worker)=><option key={w.id} value={w.id}>{w.display_name}</option>)}</select><select value={filterAction} onChange={e=>setFilterAction(e.target.value)}><option value="">Acciones</option>{(data.rules||[]).map((r:Rule)=><option key={r.action_key} value={r.action_key}>{r.name}</option>)}</select></div></div>{events.length?events.map((e:any)=>{const w=(data.workers||[]).find((x:Worker)=>x.id===e.worker_id);const r=(data.rules||[]).find((x:Rule)=>x.action_key===e.action_key);return <div className={styles.event} key={e.id}><div><strong>{w?.display_name||"Telefonista"}</strong><span>{r?.name||e.action_key}</span><small>{new Date(e.created_at).toLocaleString("es-ES")} · {e.reference_label||e.origin||"Sistema"}</small></div><b className={e.xp_amount>=0?styles.plus:styles.minus}>{e.xp_amount>=0?"+":""}{fmt(e.xp_amount)} XP</b></div>}):<div className={styles.empty}>Todavía no hay eventos XP registrados.</div>}</div>
 </section>
}
function RuleCard({rule,save,busy}:{rule:Rule;save:(r:Rule)=>void;busy:boolean}){const [r,setR]=useState(rule);useEffect(()=>setR(rule),[rule]);return <article className={styles.rule}><div className={styles.ruleTitle}><div><strong>{r.name}</strong><small>{r.action_key}</small></div><span className={r.integration_status==="connected"?styles.connected:styles.pending}>{r.integration_status==="connected"?"Conectada":"Pendiente de integración"}</span></div><p>{r.description}</p><div className={styles.ruleControls}><label>XP otorgado<input type="number" min="0" value={r.xp_reward} onChange={e=>setR({...r,xp_reward:Number(e.target.value)})}/></label><label>Frecuencia<input value={r.frequency} onChange={e=>setR({...r,frequency:e.target.value})}/></label><label className={styles.switch}><input type="checkbox" checked={r.enabled} onChange={e=>setR({...r,enabled:e.target.checked})}/><span>{r.enabled?"Activa":"Desactivada"}</span></label><button disabled={busy} onClick={()=>save(r)}><Save size={15}/> Guardar</button></div></article>}
function NewRule({onClose,onSave}:{onClose:()=>void;onSave:(r:Rule)=>void}){const [r,setR]=useState<Rule>({action_key:"",name:"",description:"",xp_reward:0,frequency:"",enabled:true,integration_status:"pending"});return <div className={styles.backdrop}><div className={styles.modal}><h2>Nueva acción XP</h2><label>Nombre<input value={r.name} onChange={e=>setR({...r,name:e.target.value})}/></label><label>Clave interna<input value={r.action_key} onChange={e=>setR({...r,action_key:e.target.value})}/></label><label>Descripción<textarea value={r.description} onChange={e=>setR({...r,description:e.target.value})}/></label><label>XP<input type="number" value={r.xp_reward} onChange={e=>setR({...r,xp_reward:Number(e.target.value)})}/></label><label>Frecuencia<input value={r.frequency} onChange={e=>setR({...r,frequency:e.target.value})}/></label><p>Las acciones nuevas nacen como <b>Pendiente de integración</b>: configurarlas no inventa un evento.</p><div><button onClick={onClose}>Cancelar</button><button onClick={()=>onSave(r)}>Crear acción</button></div></div></div>}
