import type { Metadata } from "next";
import PublicBusinessShell, { LegalDocument } from "@/components/public/PublicBusinessShell";
import { BUSINESS, PRICES } from "@/lib/public-business";

export const metadata: Metadata = { title: "Términos y condiciones | Tarot Celestial", description: "Condiciones de contratación y uso de los servicios de Tarot Celestial.", alternates: { canonical: `${BUSINESS.website}/terminos` } };

export default function TermsPage() {
  return <PublicBusinessShell activePath="/terminos"><LegalDocument eyebrow="Información legal" title="Términos y condiciones" intro="Condiciones generales para contratar y utilizar los servicios de Tarot Celestial.">
    <section><h2>1. Identificación</h2><p>El servicio se presta bajo el nombre comercial <strong>{BUSINESS.commercialName}</strong>, cuyo titular es <strong>{BUSINESS.legalName}</strong>, NIF/NIE {BUSINESS.taxId}, con domicilio en {BUSINESS.addressLines.join(", ")}. Contacto: <a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a> y <a href={`tel:${BUSINESS.phoneHref}`}>{BUSINESS.phoneDisplay}</a>.</p></section>
    <section><h2>2. Objeto del servicio</h2><p>Tarot Celestial ofrece consultas privadas de tarot y orientación personal mediante llamadas telefónicas. El servicio tiene una finalidad de entretenimiento y orientación; no constituye ni sustituye asesoramiento médico, psicológico, jurídico o financiero, ni garantiza acontecimientos o resultados.</p></section>
    <section><h2>3. Contratación y precios</h2><p>Antes del pago se informa de la duración, precio y características del paquete. Los precios vigentes son: {PRICES.map((item) => `${item.minutes} minutos — ${item.price}`).join("; ")}. Todos se expresan en euros (EUR).</p><p>La contratación queda confirmada cuando el proveedor de pagos autoriza la operación y el paquete queda asociado al cliente. El cliente debe facilitar datos correctos y disponer de capacidad legal para contratar.</p></section>
    <section><h2>4. Prestación y disponibilidad</h2><p>Los minutos adquiridos se consumen durante la consulta telefónica. La atención depende de la disponibilidad operativa del equipo y de las líneas. Si una incidencia técnica atribuible a Tarot Celestial impide prestar el servicio, se ofrecerá una solución razonable, que podrá consistir en reprogramación, restitución de minutos o reembolso cuando corresponda.</p></section>
    <section><h2>5. Pagos</h2><p>El pago se procesa mediante los proveedores mostrados durante la compra. Tarot Celestial no solicita que se comuniquen datos completos de tarjeta por correo o teléfono. El cliente debe utilizar medios de pago propios o autorizados.</p></section>
    <section><h2>6. Cancelaciones y desistimiento</h2><p>Las cancelaciones, reembolsos y el derecho de desistimiento se regulan en la <a href="/reembolsos">Política de cancelaciones y reembolsos</a>. Ninguna disposición de estas condiciones limita los derechos que la normativa de consumidores reconozca al cliente.</p></section>
    <section><h2>7. Uso correcto</h2><p>No se permite utilizar el servicio para realizar amenazas, acoso, actividades ilícitas, suplantaciones o intentos de acceso no autorizado. Tarot Celestial podrá interrumpir una consulta ante conductas abusivas, preservando los derechos legales del consumidor.</p></section>
    <section><h2>8. Responsabilidad</h2><p>Las decisiones personales tomadas después de una consulta corresponden exclusivamente al cliente. Tarot Celestial responde en los términos exigidos por la legislación aplicable, pero no garantiza resultados basados en interpretaciones de tarot.</p></section>
    <section><h2>9. Contacto y legislación aplicable</h2><p>Para consultas o reclamaciones, escribe a <a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a>. Estas condiciones se rigen por la legislación española, sin perjuicio de las normas imperativas de protección de consumidores y de los órganos competentes que resulten aplicables.</p></section>
  </LegalDocument></PublicBusinessShell>;
}
