"use client";
import {useMemo,useState} from "react";
import {Clock3,Coins,Crown,Gift,Gem,LockKeyhole,Sparkles,Vault} from "lucide-react";
import {useCentralStore,type StoreReward} from "./useCentralStore";
import styles from "./CentralStorePanel.module.css";
const categories=[{key:"all",label:"Todas",icon:Sparkles},{key:"money",label:"Dinero",icon:Coins},{key:"time",label:"Tiempo libre",icon:Clock3},{key:"surprise",label:"Sorpresas",icon:Gift},{key:"exclusive",label:"Exclusivas",icon:Gem}] as const;
const fmt=(n:number)=>Number(n||0).toLocaleString("es-ES");
export default function CentralStorePanel({onEarnCoins}:{onEarnCoins:()=>void}){const feed=useCentralStore();const[filter,setFilter]=useState("all"),[selected,setSelected]=useState<StoreReward|null>(null),[operationId,setOperationId]=useState(""),[sending,setSending]=useState(false),[message,setMessage]=useState("");const items=useMemo(()=>feed.data?.rewards.filter(r=>filter==="all"||r.category===filter)||[],[feed.data,filter]);
 function open(reward:StoreReward){setSelected(reward);setOperationId(crypto.randomUUID());setMessage("")}
 async function confirm(){if(!selected||!operationId||sending)return;setSending(true);try{await feed.claim(selected.id,operationId);setMessage("Recompensa solicitada correctamente.");setSelected(null);setOperationId("")}catch(e:any){setMessage(e.message)}finally{setSending(false)}}
 return <section className={styles.page}><header className={styles.hero}><div><span><Vault/> BÓVEDA DE RECOMPENSAS</span><h1>Tu progreso abre nuevas posibilidades</h1><p>Usa las Coins ganadas con tu progreso para solicitar recompensas configuradas por Administración.</p></div><div className={styles.balance}><small>TUS COINS DISPONIBLES</small><strong><Coins/>{fmt(feed.data?.balance||0)}</strong><button onClick={onEarnCoins}>Ganar Coins</button></div></header>{feed.error?<div className={styles.error}>{feed.error}</div>:null}{message?<div className={styles.message}>{message}</div>:null}<nav className={styles.filters}>{categories.map(({key,label,icon:Icon})=><button key={key} className={filter===key?styles.active:""} onClick={()=>setFilter(key)}><Icon/>{label}</button>)}</nav>{feed.busy&&!feed.data?<div className={styles.empty}>Abriendo la Bóveda…</div>:items.length?<div className={styles.grid}>{items.map(reward=>{const missing=Math.max(0,reward.coin_cost-(feed.data?.balance||0));const locked=reward.required_level!=null&&(feed.data?.level||1)<reward.required_level;const sold=reward.stock===0;const enabled=!missing&&!locked&&!sold;return <article className={styles.card} key={reward.id}>{reward.image_url?<img src={reward.image_url} alt="" loading="lazy"/>:<div className={styles.art}>{reward.category==="exclusive"?<Crown/>:<Gift/>}</div>}<span className={styles.badge}>{categories.find(c=>c.key===reward.category)?.label}</span><h2>{reward.name}</h2><p>{reward.description}</p><strong className={styles.price}><Coins/>{fmt(reward.coin_cost)}</strong>{locked?<small><LockKeyhole/> Requiere nivel {reward.required_level}</small>:sold?<small>Agotada</small>:missing?<small>Te faltan {fmt(missing)} Coins</small>:<small>Disponible para canjear</small>}<button disabled={!enabled} onClick={()=>open(reward)}>{enabled?"CANJEAR":"NO DISPONIBLE"}</button></article>})}</div>:<div className={styles.empty}><Gift/><h2>Todavía no hay recompensas disponibles</h2><p>Administración podrá publicarlas en esta categoría.</p></div>}<section className={styles.history}><h2>Tus solicitudes</h2>{feed.data?.claims.length?feed.data.claims.slice(0,8).map(c=><div key={c.id}><span><b>{c.reward_name}</b><small>{new Date(c.created_at).toLocaleString("es-ES")}</small></span><strong>-{fmt(c.coin_cost)} · {c.status}</strong></div>):<p>Aún no has solicitado recompensas.</p>}</section>{selected?<div className={styles.backdrop}><div className={styles.modal}><Gift/><h2>Confirmar canje</h2><p>Vas a usar <b>{fmt(selected.coin_cost)} Coins</b> para solicitar <b>{selected.name}</b>.</p><div className={styles.math}><span>Saldo actual: {fmt(feed.data?.balance||0)}</span><strong>Saldo después: {fmt((feed.data?.balance||0)-selected.coin_cost)}</strong></div><div><button onClick={()=>setSelected(null)} disabled={sending}>Cancelar</button><button onClick={()=>void confirm()} disabled={sending}>{sending?"Procesando…":"CONFIRMAR CANJE"}</button></div></div></div>:null}</section>}
