"use client";
import {useMemo,useState,useRef} from "react";
import {Banknote,CalendarDays,Clock3,Coins,Crown,Gift,Gem,History,LockKeyhole,Sparkles,Vault,X} from "lucide-react";
import {useCentralStore,type StoreReward} from "./useCentralStore";
import styles from "./CentralStorePanel.module.css";
const defaultCategories=[{key:"all",label:"Todas",icon:Sparkles},{key:"money",label:"Dinero",icon:Coins},{key:"time",label:"Tiempo libre",icon:Clock3},{key:"surprise",label:"Sorpresas",icon:Gift},{key:"exclusive",label:"Exclusivas",icon:Gem}] as const;
const labels:Record<string,string>={money:"Dinero",time:"Tiempo libre",surprise:"Sorpresa",exclusive:"Exclusiva"};
const statusLabel:Record<string,string>={pending:"Solicitada",approved:"Aprobada",delivered:"Entregada",rejected:"Rechazada",cancelled:"Cancelada"};
const fmt=(n:number)=>Number(n||0).toLocaleString("es-ES");
function RewardIcon({reward}:{reward:StoreReward}){if(reward.icon_key==="banknote"||reward.category==="money")return <Banknote/>;if(reward.icon_key==="calendar"||reward.category==="time")return <CalendarDays/>;if(reward.category==="exclusive")return <Crown/>;return <Gift/>}
export default function CentralStorePanel({onEarnCoins}:{onEarnCoins:()=>void}){
 const feed=useCentralStore();const[filter,setFilter]=useState("all"),[selected,setSelected]=useState<StoreReward|null>(null),[historyOpen,setHistoryOpen]=useState(false),[operationId,setOperationId]=useState(""),[sending,setSending]=useState(false),[message,setMessage]=useState("");
 const claimLock=useRef(false);
 const categories=[...defaultCategories,...Array.from(new Set((feed.data?.rewards||[]).map(r=>r.category))).filter(key=>!defaultCategories.some(c=>c.key===key)).map(key=>({key,label:key,icon:Gift}))];
 const items=useMemo(()=>feed.data?.rewards.filter(r=>filter==="all"||r.category===filter)||[],[feed.data,filter]);
 function open(reward:StoreReward){setSelected(reward);setOperationId(crypto.randomUUID());setMessage("")}
 async function confirm(){if(!selected||!operationId||claimLock.current)return;claimLock.current=true;setSending(true);try{await feed.claim(selected.id,operationId,selected.coin_cost);setMessage(`Has solicitado ${selected.name}. Administración gestionará la entrega.`);setSelected(null);setOperationId("")}catch(e:any){setMessage(e.message);if(e.message.startsWith("El precio ha cambiado")){setSelected(null);setOperationId("")}}finally{claimLock.current=false;setSending(false)}}
 const claims=feed.data?.claims||[];
 return <section className={styles.page}>
  <header className={styles.hero}><div><span><Vault/> BÓVEDA DE RECOMPENSAS</span><h1>Premios reales para tu progreso</h1><p>Elige tu recompensa y solicítala usando las Coins que has ganado.</p></div><div className={styles.balance}><small>TUS COINS DISPONIBLES</small><strong><Coins/>{fmt(feed.data?.balance||0)}</strong><button onClick={onEarnCoins}>Ganar Coins</button></div></header>
  {feed.error?<div className={styles.error}>{feed.error}</div>:null}{message?<div className={styles.message}><Sparkles/>{message}</div>:null}
  <nav className={styles.filters} aria-label="Categorías de recompensas">{categories.map(({key,label,icon:Icon})=><button key={key} aria-pressed={filter===key} className={filter===key?styles.active:""} onClick={()=>setFilter(key)}><Icon/>{label}</button>)}</nav>
  <div className={styles.content}><main>{feed.busy&&!feed.data?<div className={styles.empty}>Abriendo la Bóveda…</div>:items.length?<div className={styles.grid}>{items.map(reward=>{const missing=Math.max(0,reward.coin_cost-(feed.data?.balance||0));const locked=reward.required_level!=null&&(feed.data?.level||1)<reward.required_level;const sold=reward.stock===0;const enabled=!missing&&!locked&&!sold;return <article className={`${styles.card} ${styles[reward.category]}`} key={reward.id}>{reward.image_url?<img src={reward.image_url} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display="none"}}/>:<div className={styles.art}><RewardIcon reward={reward}/><i/></div>}<span className={styles.badge}>{labels[reward.category]||reward.category}{reward.featured?" · Destacada":""}</span><h2>{reward.name}</h2><p>{reward.description}</p><small>Tienes: {fmt(feed.data?.balance||0)} Coins</small><strong className={styles.price}><Coins/>{fmt(reward.coin_cost)} <small>Coins</small></strong>{locked?<span className={styles.state}><LockKeyhole/> Requiere nivel {reward.required_level}</span>:sold?<span className={styles.state}>Agotada</span>:missing?<span className={styles.state}>Te faltan {fmt(missing)} Coins</span>:<span className={styles.ready}><Sparkles/> Puedes reclamarla</span>}<button disabled={!enabled||sending} onClick={()=>open(reward)}>{sending&&selected?.id===reward.id?"RECLAMANDO…":enabled?"RECLAMAR":"NO DISPONIBLE"}</button></article>})}</div>:<div className={styles.empty}><Gift/><h2>La Bóveda está preparando nuevas recompensas</h2><p>Vuelve pronto para descubrirlas.</p></div>}</main>
   <aside className={styles.recent}><header><div><small>TU ACTIVIDAD</small><h2>Recompensas recientes</h2></div><History/></header>{claims.length?claims.slice(0,3).map(c=><article key={c.id}><div className={styles.claimIcon}>{c.reward_image_url?<img src={c.reward_image_url} alt=""/>:c.category==="money"?<Banknote/>:<Gift/>}</div><div><strong>{c.reward_name}</strong><span>{labels[c.category]||c.category}</span><small>Reclamada el {new Date(c.created_at).toLocaleDateString("es-ES")} · {statusLabel[c.status]||c.status}</small></div></article>):<p>Todavía no has reclamado ninguna recompensa.</p>}<button onClick={()=>setHistoryOpen(true)} disabled={!claims.length}><History/> VER HISTORIAL</button></aside>
  </div>
  {selected?<div className={styles.backdrop}><div className={styles.modal} role="dialog" aria-modal="true" aria-label="Confirmar recompensa"><button className={styles.close} disabled={sending} onClick={()=>setSelected(null)} aria-label="Cerrar"><X/></button><RewardIcon reward={selected}/><small>RECLAMAR RECOMPENSA</small><h2>{selected.name}</h2><div className={styles.confirmRows}><span>Coste <b><Coins/>{fmt(selected.coin_cost)} Coins</b></span><span>Tu saldo <b>{fmt(feed.data?.balance||0)} Coins</b></span><span>Después del canje <b>{fmt((feed.data?.balance||0)-selected.coin_cost)} Coins</b></span></div><p>La solicitud quedará pendiente para que Administración gestione la entrega.</p><div className={styles.modalActions}><button onClick={()=>setSelected(null)} disabled={sending}>CANCELAR</button><button onClick={()=>void confirm()} disabled={sending}>{sending?"PROCESANDO…":`CONFIRMAR POR ${fmt(selected.coin_cost)} COINS`}</button></div></div></div>:null}
  {historyOpen?<div className={styles.backdrop}><div className={`${styles.modal} ${styles.historyModal}`}><button className={styles.close} onClick={()=>setHistoryOpen(false)} aria-label="Cerrar"><X/></button><History/><small>HISTORIAL COMPLETO</small><h2>Tus recompensas</h2><div className={styles.fullHistory}>{claims.map(c=><article key={c.id}><RewardIcon reward={{category:c.category} as StoreReward}/><span><b>{c.reward_name}</b><small>{labels[c.category]||c.category} · {new Date(c.created_at).toLocaleString("es-ES")}</small></span><strong>-{fmt(c.coin_cost)} Coins<br/><small>{statusLabel[c.status]||c.status}{c.status_note?` · ${c.status_note}`:""}</small></strong></article>)}</div></div></div>:null}
 </section>
}
