"use client";
import {useCallback,useEffect,useState} from "react";
import {supabaseBrowser} from "@/lib/supabase-browser";
const sb=supabaseBrowser();
export type StoreReward={id:string;name:string;description:string;category:"money"|"time"|"surprise"|"exclusive";coin_cost:number;icon_key:string|null;image_url:string|null;active:boolean;display_order:number;stock:number|null;required_level:number|null};
export type StoreData={balance:number;level:number;rewards:StoreReward[];claims:Array<{id:string;reward_name:string;category:StoreReward["category"];coin_cost:number;status:string;created_at:string}>};
export function useCentralStore(){const[data,setData]=useState<StoreData|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const load=useCallback(async(silent=false)=>{if(!silent)setBusy(true);try{const token=(await sb.auth.getSession()).data.session?.access_token;if(!token)throw new Error("Sesión no disponible");const r=await fetch(`/api/central/store?t=${Date.now()}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"No se pudo abrir la Tienda");setData(j);setError("");return true}catch(e:any){setError(e.message);return false}finally{if(!silent)setBusy(false)}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),30000);const channel=sb.channel("central-store").on("postgres_changes",{event:"*",schema:"public",table:"worker_coin_wallets"},()=>void load(true)).on("postgres_changes",{event:"*",schema:"public",table:"worker_store_rewards"},()=>void load(true)).on("postgres_changes",{event:"*",schema:"public",table:"worker_store_claims"},()=>void load(true)).subscribe();return()=>{clearInterval(timer);void sb.removeChannel(channel)}},[load]);
 const claim=useCallback(async(rewardId:string,operationId:string)=>{const token=(await sb.auth.getSession()).data.session?.access_token;if(!token)throw new Error("Sesión no disponible");const r=await fetch("/api/central/store",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({op:"claim_reward",reward_id:rewardId,operation_id:operationId})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"No se pudo completar el canje");await load(true);return j.claim},[load]);return{data,busy,error,load,claim};}
