"use client";
import { useCallback, useEffect, useState } from "react";
import { Gift, PhoneCall, ShoppingBag, Sparkles, WandSparkles } from "lucide-react";
import ClienteLayout from "@/components/cliente/ClienteLayout";
import { supabaseBrowser } from "@/lib/supabase-browser";
import styles from "./PricesOffers.module.css";
const sb=supabaseBrowser();
type OraclePack={id:string;nombre:string;descripcion:string;priceEur:number;credits:number}; type MinutePack={id:string;nombre:string;descripcion:string;priceUsd:number;totalMinutes:number;bonusMinutes:number;highlight?:boolean};
export default function PreciosOfertasPage(){
 const [oraclePacks,setOraclePacks]=useState<OraclePack[]>([]),[minutePacks,setMinutePacks]=useState<MinutePack[]>([]); const [freeAvailable,setFreeAvailable]=useState(false),[credits,setCredits]=useState(0),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const {data}=await sb.auth.getSession();const token=data.session?.access_token;if(!token){window.location.href="/cliente/login";return}const [o,m]=await Promise.all([fetch("/api/cliente/oraculo",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"}),fetch("/api/cliente/me",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"})]);const oj=await o.json().catch(()=>null),mj=await m.json().catch(()=>null);if(oj?.ok){setOraclePacks(Array.isArray(oj.packs)?oj.packs:[]);setCredits(Number(oj.credits||0));setFreeAvailable(Boolean(oj.freeDailyAvailable??oj.freeAvailable))}if(mj?.ok)setMinutePacks(Array.isArray(mj.packs)?mj.packs:[])},[]);
 useEffect(()=>{load()},[load]);
 async function checkout(endpoint:string,packId:string){try{setBusy(packId);setMessage("");const {data}=await sb.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Sesión no válida");const r=await fetch(endpoint,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({pack_id:packId})});const j=await r.json().catch(()=>null);if(!j?.ok||!j?.url)throw new Error(j?.error||"No hemos podido iniciar el pago");window.location.href=j.url}catch(e:any){setMessage(e?.message||"No hemos podido iniciar el pago")}finally{setBusy("")}}
 const total=credits+(freeAvailable?1:0);
 return <ClienteLayout title="Precios y ofertas" subtitle="Descubre tus opciones, ventajas y promociones disponibles." summaryItems={[{label:"Tiradas disponibles",value:String(total),meta:freeAvailable?`1 gratis hoy · ${credits} compradas`:`${credits} compradas`,href:"/cliente/oraculo",tone:"oracle"},{label:"Packs Oráculo",value:String(oraclePacks.length),meta:"Productos reales disponibles"},{label:"Packs de minutos",value:String(minutePacks.length),meta:"Opciones actuales de consulta"}]}><div className={styles.shell}>{message?<div className={styles.message}>{message}</div>:null}
 <section className={styles.hero}><Sparkles/><div><span>TIENDA CELESTIAL</span><h1>Desbloquea nuevas experiencias</h1><p>Todos los precios proceden de los productos reales ya configurados en tu cuenta.</p></div></section>
 <section className={styles.section}><div className={styles.heading}><WandSparkles/><div><h2>Tiradas del Oráculo</h2><p>Créditos mágicos independientes de Coins y minutos.</p></div></div><div className={styles.grid}>{oraclePacks.map((p,i)=><article key={p.id} className={`${styles.card} ${i===1?styles.featured:""}`}><div className={styles.icon}>{i===0?"🔮":"✨"}</div><span className={styles.badge}>{p.credits} TIRADAS</span><h3>{p.nombre}</h3><p>{p.descripcion}</p><strong className={styles.price}>{p.priceEur.toFixed(2).replace(".",",")} €</strong><button disabled={busy===p.id} onClick={()=>checkout("/api/cliente/oraculo/checkout",p.id)}>{busy===p.id?"Conectando…":"COMPRAR"}</button></article>)}</div></section>
 <section className={styles.section}><div className={styles.heading}><PhoneCall/><div><h2>Consultas / Minutos</h2><p>Las opciones actuales del mismo sistema de compra de minutos.</p></div></div><div className={styles.grid}>{minutePacks.map(p=><article key={p.id} className={`${styles.card} ${p.highlight?styles.featured:""}`}><div className={styles.icon}><ShoppingBag/></div>{p.highlight?<span className={styles.badge}>RECOMENDADO</span>:null}<h3>{p.nombre}</h3><p>{p.descripcion}</p><strong className={styles.price}>${p.priceUsd.toFixed(2)} USD</strong><small>{p.totalMinutes} minutos totales</small><button disabled={busy===p.id} onClick={()=>checkout("/api/cliente/pagos/checkout",p.id)}>{busy===p.id?"Conectando…":"COMPRAR"}</button></article>)}</div></section>
 <section className={`${styles.section} ${styles.coming}`}><Gift/><div><span>OFERTAS</span><h2>Nuevas promociones próximamente</h2><p>Este espacio queda preparado para promociones reales, sin inventar descuentos ni ventajas que todavía no estén activas.</p></div></section>
 </div></ClienteLayout>}
