import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { getAuthUserFromRequest } from "@/lib/server/auth-fast";

export const dynamic = "force-dynamic";
function env(name:string){const value=process.env[name];if(!value)throw new Error(`Missing env var: ${name}`);return value}
function adminClient(){return createClient(env("NEXT_PUBLIC_SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false}})}
async function requireAdmin(req:Request){const {data,error}=getAuthUserFromRequest(req);if(error||!data.user?.id)return null;const admin=adminClient();const {data:worker,error:workerError}=await admin.from("workers").select("id,role").eq("user_id",data.user.id).maybeSingle();if(workerError)throw workerError;return worker?.role==="admin"?worker:null}

export async function GET(req:Request){try{const me=await requireAdmin(req);if(!me)return NextResponse.json({ok:false,error:"FORBIDDEN"},{status:403});const admin=adminClient();const [{data:assignments,error:aError},{data:workers,error:wError},{data:audit,error:hError}]=await Promise.all([
  admin.from("crm_client_capture_assignments").select("*").order("updated_at",{ascending:false}).limit(1000),
  admin.from("workers").select("id,display_name,team,role,is_active").eq("role","central").order("display_name"),
  admin.from("crm_client_capture_audit").select("*").order("created_at",{ascending:false}).limit(500),
]);if(aError)throw aError;if(wError)throw wError;if(hError)throw hError;const clientIds=(assignments||[]).map((x:any)=>x.client_id);const {data:clients,error:cError}=clientIds.length?await admin.from("crm_clientes").select("id,nombre,apellido,telefono,origen").in("id",clientIds):{data:[],error:null};if(cError)throw cError;const clientMap=new Map((clients||[]).map((x:any)=>[String(x.id),x]));const workerMap=new Map((workers||[]).map((x:any)=>[String(x.id),x]));return NextResponse.json({ok:true,workers:(workers||[]).filter((x:any)=>x.is_active!==false),items:(assignments||[]).map((x:any)=>({...x,client:clientMap.get(String(x.client_id))||null,captured_by:workerMap.get(String(x.captured_by_worker_id))||null,responsible:workerMap.get(String(x.responsible_worker_id))||null,candidate:workerMap.get(String(x.candidate_worker_id))||null,audit:(audit||[]).filter((h:any)=>String(h.client_id)===String(x.client_id)).slice(0,10).map((h:any)=>({...h,previous_name:workerMap.get(String(h.previous_responsible_worker_id))?.display_name||null,new_name:workerMap.get(String(h.new_responsible_worker_id))?.display_name||null,actor_name:workerMap.get(String(h.actor_worker_id))?.display_name||"Admin"}))}))});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||"ERR_CLIENT_CAPTURES"},{status:500})}}

export async function POST(req:Request){try{const me=await requireAdmin(req);if(!me)return NextResponse.json({ok:false,error:"FORBIDDEN"},{status:403});const body=await req.json().catch(()=>({}));const clientId=String(body.client_id||"");const workerId=String(body.responsible_worker_id||"");if(!clientId||!workerId)return NextResponse.json({ok:false,error:"FIELDS_REQUIRED"},{status:400});const admin=adminClient();const {data,error}=await admin.rpc("reassign_client_capture_responsible",{p_client_id:clientId,p_new_worker_id:workerId,p_actor_worker_id:me.id,p_reason:String(body.reason||"")});if(error)throw error;return NextResponse.json({ok:true,data});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||"ERR_REASSIGN_CAPTURE"},{status:500})}}
