import type { Metadata } from "next";
import PublicBusinessShell, { LegalDocument } from "@/components/public/PublicBusinessShell";
import styles from "@/components/public/PublicBusiness.module.css";
import { BUSINESS } from "@/lib/public-business";

export const metadata: Metadata = { title: "Cancelaciones y reembolsos | Tarot Celestial", description: "Política de cancelaciones, desistimiento y reembolsos de Tarot Celestial.", alternates: { canonical: `${BUSINESS.website}/reembolsos` } };

export default function RefundsPage() {
  return <PublicBusinessShell activePath="/reembolsos"><LegalDocument eyebrow="Protección del cliente" title="Cancelaciones y reembolsos" intro="Cómo solicitar una cancelación, comunicar una incidencia o ejercer los derechos que correspondan.">
    <section><h2>1. Solicitudes</h2><p>Para solicitar una cancelación o reembolso, escribe a <a href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a> indicando el nombre del comprador, fecha, importe, referencia de la operación y motivo. No incluyas el número completo de una tarjeta ni su código de seguridad.</p></section>
    <section><h2>2. Derecho de desistimiento</h2><p>Cuando la normativa española de consumidores resulte aplicable, el cliente dispone con carácter general de catorce días naturales desde la celebración del contrato de servicios para comunicar su desistimiento.</p><p>Si el cliente solicita expresamente que la consulta comience durante ese plazo, podrá corresponder el pago proporcional de la parte ya prestada. Cuando el servicio haya sido completamente ejecutado, el derecho de desistimiento podrá extinguirse si la ejecución comenzó con el consentimiento expreso del cliente y con su conocimiento de que perdería ese derecho una vez completado el servicio.</p><p className={styles.notice}>Esta política no reduce los derechos que correspondan legalmente al consumidor. Cada solicitud se revisará atendiendo al estado real de la prestación y a la normativa aplicable.</p></section>
    <section><h2>3. Minutos no utilizados</h2><p>Si el servicio aún no ha comenzado y procede el desistimiento o una cancelación aceptada, se tramitará la devolución correspondiente. Si parte del paquete ya fue utilizada a petición del cliente, se podrá deducir el importe proporcional al servicio efectivamente prestado cuando la ley lo permita.</p></section>
    <section><h2>4. Incidencias técnicas</h2><p>Si una incidencia atribuible a Tarot Celestial impide prestar total o parcialmente la consulta, el cliente podrá solicitar revisión. Según el caso, se ofrecerá reprogramación, restitución de minutos o reembolso total o parcial. No se considerará consumido el tiempo que no haya podido prestarse por una incidencia confirmada del servicio.</p></section>
    <section><h2>5. Pagos duplicados o no reconocidos</h2><p>Los cobros duplicados confirmados serán reembolsados. Si no reconoces una operación, comunícalo cuanto antes para investigarla y contacta también con tu proveedor de pago. Podremos solicitar información que permita verificar la identidad y la operación.</p></section>
    <section><h2>6. Plazo y forma del reembolso</h2><p>Una vez aprobado, el reembolso se ordenará por el mismo medio de pago utilizado siempre que sea posible. El tiempo hasta que aparezca en la cuenta puede depender del banco o proveedor de pagos. Informaremos al cliente cuando la devolución haya sido tramitada.</p></section>
    <section><h2>7. Exclusiones legítimas</h2><p>No procederá un reembolso por el mero desacuerdo con una interpretación de tarot o por no obtener un resultado esperado, dado que no se garantizan predicciones ni resultados. Esto no afecta a reclamaciones por falta de prestación, cobros incorrectos, incumplimiento o cualquier otro derecho legal.</p></section>
    <section><h2>8. Reclamaciones</h2><p>Si no estás conforme con la solución, puedes responder al mismo correo para solicitar una segunda revisión y utilizar las vías de reclamación y protección de consumidores que legalmente correspondan.</p></section>
  </LegalDocument></PublicBusinessShell>;
}
